import 'dart:convert';
import 'package:custom_selectable_text/custom_selectable_text.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:lottie/lottie.dart';
import 'package:qwizapp/All_Models/CModel.dart';

import '../CategoryWidgets/AllColors.dart';

class CQuestion extends StatefulWidget {
  const CQuestion({super.key});

  @override
  State<CQuestion> createState() => _CQuestionState();
}

class _CQuestionState extends State<CQuestion> {
  List<Autogenerated> samplepost = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: appCustomTextFieldErrorOutlineDarkColor,
      body: Container(
          color: Colors.white,
          child: FutureBuilder(
              future: getdata(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  return ListView.builder(
                      itemCount: samplepost.length,
                      itemBuilder: (context, index) {
                        return Container(
                          height: 350,
                          decoration: BoxDecoration(
                              color: Colors.greenAccent,
                              borderRadius: BorderRadius.circular(10)),
                          padding: const EdgeInsets.symmetric(
                              horizontal: 10, vertical: 10),
                          margin: const EdgeInsets.all(10),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                "Id: ${samplepost[index].id}",
                                style: const TextStyle(
                                    fontSize: 18, color: Colors.black),
                              ),
                              Text(
                                "PostId: ${samplepost[index].postId}",
                                style: const TextStyle(
                                    fontSize: 18, color: Colors.white),
                              ),
                              Text(
                                "Name: ${samplepost[index].name}",
                                style: const TextStyle(
                                    fontSize: 18, color: Colors.white),
                              ),
                              CustomSelectableText(
                                "Email,:, ${samplepost[index].email}",
                                items: [
                                  CustomSelectableTextItem.icon(
                                      icon: const Icon(Icons.copy),
                                      controlType: SelectionControlType.copy,
                                      onPressed: (text) {
                                        ScaffoldMessenger.of(context)
                                            .showSnackBar(SnackBar(
                                          content: Text("Copied $text text"),
                                        ));
                                      }),
                                  CustomSelectableTextItem.icon(
                                    controlType: SelectionControlType.selectAll,
                                    icon: const Icon(Icons.select_all),
                                  ),
                                  CustomSelectableTextItem.icon(
                                      icon: const Icon(Icons.share),
                                      onPressed: (text) {
                                        ScaffoldMessenger.of(context)
                                            .showSnackBar(SnackBar(
                                          content: Text("Shared $text text"),
                                        ));
                                      }),
                                  // CustomSelectableTextItem.popUpMenuButton(
                                  //     child: PopupMenuButton(
                                  //       itemBuilder: (context) =>
                                  //       [
                                  //         const PopupMenuItem(
                                  //           child: Text("Text 1"),
                                  //         ),
                                  //         const PopupMenuItem(
                                  //           child: Text("Text 2"),
                                  //         ),
                                  //       ],
                                  //     )),
                                ],
                                style: const TextStyle(
                                    fontSize: 18, color: Colors.white),
                              ),
                              Text(
                                "Body: ${samplepost[index].body}",
                                style: const TextStyle(
                                    fontSize: 18, color: Colors.white),
                              ),
                            ],
                          ),
                        );
                      });
                } else {
                  return Center(
                    child: Lottie.network(
                        'https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/Mobilo/A.json'),
                  );
                }
              })),
    );
  }

  Future<List<Autogenerated>> getdata() async {
    final responce = await http
        .get(Uri.parse('https://jsonplaceholder.typicode.com/comments'));
    var data = jsonDecode(responce.body.toString());
    if (responce.statusCode == 200) {
      for (Map<String, dynamic> index in data) {
        samplepost.add(Autogenerated.fromJson(index));
      }
      return samplepost;
    } else {
      return samplepost;
    }
  }
}
